### ISSUE TITLE
Missing "Softmax" class and the problem of linking "MO586rl_glue.exe".

### ISSUE THREAD

**Issue by rupamB** [FedUni/MORL#1]
Dear Creator,
Currently, I try to run your MORL project where I am using:

1. Windows 10 (64 bit).
2. Eclipse IDE.
3. Create a new Java project and **JavaRLGlueCodec.jar is successfully** added as external jar.
4.    **MORL environment**: GeneralisedDeepSeaTreasureEnv
       **MORL Agent:** TLO_Agent
       **Experiment:** DemoExperiment

Following **issues** arise while running "MORL_Glue_Driver.java"

1. In **"TLO_LookupTable.java"**, following line is creating the error:
   
 

>   `return Softmax.getAction(scores,temperature,best);`

   
   **The "Softmax" class could not be found.**
   
2. Not able get the **"MO586rl_glue.exe"** as mentioned in the readMe file.

3. Following screenshot will help to resolve the issues in a clear way.

1. Error Screenshot [error0](https://pasteboard.co/GS2Hp7f.png) and [error1](https://pasteboard.co/GS2HFJr.png)
2. Current [output](https://pasteboard.co/GS2P788.png)

The above **output is static** (not as claimed by the the video) due to the errors.

Thank you in advance for addressing the issues.

**Comment by morphcogn** [comment]
Hi,

Firstly it appears that you are using an old version of the multi-objective
RL server executable file. Where did you get this file from, was this from
our repository ?

Sorry I think also the wrong version of the softmax Java file may have been
put up on the repository, we will check that on Monday and get back to you.

Thank you,
Dean

**Comment by rupamB** [comment]
Dear Dean,
Thanks for your reply. All the content regarding MORL has been downloaded from this github [source] (https://github.com/FedUni/MORL).

1. I am not able to find out the server executable (MO586rl_glue.exe ?) from the repo.
2. Where does the "Softmax" java file exist in the repo?
Best,
Rupam

**Comment by cocoademon** [comment]
Hi Rupam,

Thanks for letting us know about these issues.

The missing `Softmax.java` was an oversight, and is now included in the repository under `morlglue-clients/tools/valuefunction/`.

Could you please grab the Windows server executable from https://github.com/FedUni/MORL/releases? It should be in `morlglue.zip`. 

Finally, at the moment you will need to update your local `MORL_Glue_Driver.java` to point at the location of the MORL-Glue server on line 16; alternatively you could comment out lines 14-23 and start the server manually.

**Comment by rupamB** [comment]
Hi,
Many thanks for your modifications and comments. Now, it is running perfectly in my machine.
Are there any google group for discussing important topics about MORL?

Best,
Rupam
